server {
  listen 8080;

  location = /health {
    default_type application/json;
    return 200 '{"status":"UP","service":"api-gateway"}';
  }

  location /users/health { proxy_pass http://user-service:5001/health; }
  location /products/health { proxy_pass http://product-service:5002/health; }
  location /orders/health { proxy_pass http://order-service:5003/health; }

  location /users { proxy_pass http://user-service:5001/users; }
  location /products { proxy_pass http://product-service:5002/products; }
  location /orders { proxy_pass http://order-service:5003/orders; }
}
