sonar.projectKey=ecommerce-microservices-demo
sonar.projectName=E-Commerce Microservices Demo
sonar.sources=services,frontend/src,api-gateway
sonar.exclusions=**/tests/**,**/node_modules/**,**/.venv/**
sonar.python.version=3.12
