apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: REPLACE_ECR/ecommerce/order-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5003
          env:
            - name: DB_HOST
              value: order-db
            - name: DB_NAME
              value: orders
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: ecommerce-db-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecommerce-db-secret
                  key: DB_PASSWORD
          readinessProbe:
            httpGet:
              path: /health
              port: 5003
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: ecommerce
  labels:
    app: order-service
spec:
  selector:
    app: order-service
  ports:
    - name: http
      port: 5003
      targetPort: 5003
